#!/usr/bin/env bash

# Copyright (c) 2012 Dickson S. Guedes.
#
# This module is free software; you can redistribute it and/or modify it under
# the [PostgreSQL License](http://www.opensource.org/licenses/postgresql).
#
# Permission to use, copy, modify, and distribute this software and its
# documentation for any purpose, without fee, and without a written agreement is
# hereby granted, provided that the above copyright notice and this paragraph
# and the following two paragraphs appear in all copies.
#
# In no event shall Dickson S. Guedes be liable to any party for direct,
# indirect, special, incidental, or consequential damages, including lost
# profits, arising out of the use of this software and its documentation, even
# if Dickson S. Guedes has been advised of the possibility of such damage.
#
# Dickson S. Guedes specifically disclaims any warranties, including, but not
# limited to, the implied warranties of merchantability and fitness for a
# particular purpose. The software provided hereunder is on an "as is" basis,
# and Dickson S. Guedes has no obligations to provide maintenance, support,
# updates, enhancements, or modifications.

source $pgvm_home/actions/current

usage()
{
	echo """
Manipulates clusters within pgvm.

Usage: pgvm cluster <action> <args>

  - action

    create      Creates a new cluster (PGDATA)
    remove      Removes a cluster
    rename      Renames a cluster
    list        List all clusters

    import      Import a cluster from tarball
    export      Export a cluster to tarball
"""
}

cluster()
{
	action=$1		; shift

	[[ -z "$action" ]] && usage && exit 1

	$action $@
}

create()
{
	cluster_name=$1 ; shift

	[[ -z "$cluster_name" ]] && echo "please, choose a name for cluster!" && exit 1

	cluster_top_dir="$pgvm_home/clusters/$(current)"
	cluster_dir="${cluster_top_dir}/${cluster_name}"

	[[ -d "$cluster_dir" ]] && echo "cluster '${cluster_dir}' already exists!" && exit 1

	mkdir --parents $cluster_top_dir
	mkdir --parents $pgvm_home/logs

	echo -n "initializing cluster in '$cluster_dir'... "
	$pgvm_home/environments/current/bin/initdb -D $cluster_dir 1> $pgvm_home/logs/install.$cluster_name@$(current).log 2>$pgvm_home/logs/install.$cluster_name@$(current).error.log

	[[ $? -ne 0 ]] && echo "error!" && cat $pgvm_home/logs/install.$cluster_name@$(current).error.log && exit 1

	last_port=$(find $pgvm_home/clusters -name "postgresql.conf" -exec egrep "port =" {} \; | awk '{ printf $3"\n" ;}' | sort -n | tail -1)
	next_port=$(($last_port + 1))

	echo -e "\n# added by 'pgvm' at `date`" >> $cluster_dir/postgresql.conf
	echo "port = $next_port" >> $cluster_dir/postgresql.conf

	echo "ok!"
}

list()
{
	cluster_top_dir="$pgvm_home/clusters/$(current)"
	clusters=$(find ${cluster_top_dir}/* -maxdepth 0 -type d -exec basename {} \; 2> /dev/null)

	[[ -z "$clusters" ]] && echo "there is no clusters in current environment ($(current))" && exit 1

	echo -e "cluster in current enviroment ($(current)):\n"

	for cluster in ${clusters}
	do
		echo "$cluster"
	done
}

start()
{
	cluster_ctl start $1
}

stop()
{
	cluster_ctl stop $1
}

cluster_ctl()
{
	action=$1
	cluster_name=$2
	cluster_top_dir="$pgvm_home/clusters/$(current)"
	cluster_dir=${cluster_top_dir}/${cluster_name}

	$pgvm_home/environments/current/bin/pg_ctl -D $cluster_dir $action
}

use()
{
	echo "not implemented" && exit 1
	cluster_top_dir="$pgvm_home/clusters/$(current)"
	cluster_name=${1}
	cluster="${cluster_top_dir}/${cluster_name}"

	[[ -f "$cluster/PG_VERSION" ]] && [[ ! -e "$cluster/" ]]
}

remove()
{
	echo "not implemented" && exit 1
	cluster=${1}

	echo -n "removing cluster '$cluster'"
}
