#!/usr/bin/env bash

# Copyright (c) 2012 Dickson S. Guedes.
#
# This module is free software; you can redistribute it and/or modify it under
# the [PostgreSQL License](http://www.opensource.org/licenses/postgresql).
#
# Permission to use, copy, modify, and distribute this software and its
# documentation for any purpose, without fee, and without a written agreement is
# hereby granted, provided that the above copyright notice and this paragraph
# and the following two paragraphs appear in all copies.
#
# In no event shall Dickson S. Guedes be liable to any party for direct,
# indirect, special, incidental, or consequential damages, including lost
# profits, arising out of the use of this software and its documentation, even
# if Dickson S. Guedes has been advised of the possibility of such damage.
#
# Dickson S. Guedes specifically disclaims any warranties, including, but not
# limited to, the implied warranties of merchantability and fitness for a
# particular purpose. The software provided hereunder is on an "as is" basis,
# and Dickson S. Guedes has no obligations to provide maintenance, support,
# updates, enhancements, or modifications.

source $pgvm_home/actions/cluster

usage()
{
    echo """
Starts psql and connects to a specified cluster.

Usage: pgvm console <cluster_name>[@version]

  Examples:
           pgvm console
           pgvm console some_cluster
           pgvm console test@9.1.5
           pgvm console other_cluster@9.2.0
           echo "select * from pg_stat_activity" | pgvm console some_cluster
"""
}

console()
{
    candidate=$(first_online_cluster)

    cluster_name=""
    cluster_version=""

    if [ -n "$1" ]
    then
      if echo $1 | grep @ >/dev/null
      then
        cluster_name=$(echo $1|cut -d@ -f1)
        cluster_version=$(echo $1|cut -d@ -f2)
      else
        cluster_name=$1
        cluster_version=${cluster_version:-"$(current_version)"}
      fi
    elif [ -n "$candidate" ]
    then
      cluster_name=$candidate
      cluster_version=${cluster_version:-"$(current_version)"}
    else
      echo "please, choose a cluster to connect" && exit 1
    fi

    [[ "$(cluster_human_status $cluster_name $cluster_version)" == "offline" ]] && echo "the cluster '$cluster_name' seems to be offline" && exit 1

    port=$(cluster_port $cluster_name $cluster_version)

    echo "connecting to cluster '$cluster_name' on port '$port' ..."
    echo
    ${pgvm_environments}/$cluster_version/bin/psql -p $port -d postgres
}
