#!/usr/bin/env bash

# Copyright (c) 2012 Dickson S. Guedes.
#
# This module is free software; you can redistribute it and/or modify it under
# the [PostgreSQL License](http://www.opensource.org/licenses/postgresql).
#
# Permission to use, copy, modify, and distribute this software and its
# documentation for any purpose, without fee, and without a written agreement is
# hereby granted, provided that the above copyright notice and this paragraph
# and the following two paragraphs appear in all copies.
#
# In no event shall Dickson S. Guedes be liable to any party for direct,
# indirect, special, incidental, or consequential damages, including lost
# profits, arising out of the use of this software and its documentation, even
# if Dickson S. Guedes has been advised of the possibility of such damage.
#
# Dickson S. Guedes specifically disclaims any warranties, including, but not
# limited to, the implied warranties of merchantability and fitness for a
# particular purpose. The software provided hereunder is on an "as is" basis,
# and Dickson S. Guedes has no obligations to provide maintenance, support,
# updates, enhancements, or modifications.


source $pgvm_home/include/sites

usage()
{
	echo """
Usage: pgvm install <version>

  <version> is the postgres semantic version that
            you want to install, a branch or a
            commit hash from postgresql git repo.

  Examples:
           pgvm install 9.0.7
           pgvm install 9.1.3
           pgvm install master
           pgvm install c89bdf7690

  You can pass MAKE_OPTS and CONFIG_OPTS for
  'make' and 'configure' respectively

  Examples:
           CONFIG_OPTS=\"--enable-cassert\" MAKE_OPTS=\"-j 16\" pgvm install 9.1.4

"""
}

install()
{
  version=$1
  if [ -z $version ] 
  then
	usage
  	exit
  
  else
    if seems_to_be_from_repo "$version"
    then
      if local_repo_exists
      then
        checkout_postgres $version
      else
        clone_postgres
      fi
    else
      get_postgres
      extract_postgres
    fi
  fi
	compile_and_install_postgres
}
