#!/usr/bin/env bash

# Copyright (c) 2012 Dickson S. Guedes.
#
# This module is free software; you can redistribute it and/or modify it under
# the [PostgreSQL License](http://www.opensource.org/licenses/postgresql).
#
# Permission to use, copy, modify, and distribute this software and its
# documentation for any purpose, without fee, and without a written agreement is
# hereby granted, provided that the above copyright notice and this paragraph
# and the following two paragraphs appear in all copies.
#
# In no event shall Dickson S. Guedes be liable to any party for direct,
# indirect, special, incidental, or consequential damages, including lost
# profits, arising out of the use of this software and its documentation, even
# if Dickson S. Guedes has been advised of the possibility of such damage.
#
# Dickson S. Guedes specifically disclaims any warranties, including, but not
# limited to, the implied warranties of merchantability and fitness for a
# particular purpose. The software provided hereunder is on an "as is" basis,
# and Dickson S. Guedes has no obligations to provide maintenance, support,
# updates, enhancements, or modifications.

list()
{

	VERSIONS=$(ls -1 -d $pgvm_home/environments/* 2>/dev/null | grep -v current 2> /dev/null)

	[[ -z $VERSIONS ]] && echo -e "Please, install a PostgreSQL Version!\n" && exit 0

	echo -e "PostgreSQL Installed Version:\n"

	current_path=$(readlink $pgvm_home/environments/current)

	for path in ${VERSIONS}
	do
		is_current=""
		[[ "$current_path" == "$path" ]] && is_current="=>"

		postgres_executable=$path/bin/postgres
		pg_config=$path/bin/pg_config

		if [ -f $pg_config ] && [ -f $postgres_executable ]
		then
			#banner=$( ${pg_config} --version )
			banner=$(basename $path)
			binary_info=$(file -e elf $postgres_executable | cut -d: -f2-)

			printf "%3s %-10s\n" "$is_current" "$banner"
		fi
	done
}
