#!/usr/bin/env bash

# Copyright (c) 2012 Dickson S. Guedes.
#
# This module is free software; you can redistribute it and/or modify it under
# the [PostgreSQL License](http://www.opensource.org/licenses/postgresql).
#
# Permission to use, copy, modify, and distribute this software and its
# documentation for any purpose, without fee, and without a written agreement is
# hereby granted, provided that the above copyright notice and this paragraph
# and the following two paragraphs appear in all copies.
#
# In no event shall Dickson S. Guedes be liable to any party for direct,
# indirect, special, incidental, or consequential damages, including lost
# profits, arising out of the use of this software and its documentation, even
# if Dickson S. Guedes has been advised of the possibility of such damage.
#
# Dickson S. Guedes specifically disclaims any warranties, including, but not
# limited to, the implied warranties of merchantability and fitness for a
# particular purpose. The software provided hereunder is on an "as is" basis,
# and Dickson S. Guedes has no obligations to provide maintenance, support,
# updates, enhancements, or modifications.

LS=$(which ls)

usage()
{
cat << EOF

Usage: pgvm uninstall [OPTIONS] <version>

  <version> is the postgres semantic version that
            you want to uninstall.

  Examples:
           pgvm uninstall 9.0.7
           pgvm uninstall 9.1.3
           pgvm uninstall master
           pgvm uninstall c89bdf7690

== Options

  --all     Remove all postgres versions installed.


  --purge   Remove all postgres versions installed 
            and all versions source code.
  

EOF
}

uninstall()
{
	VERSIONS=$($LS -1 $pgvm_home/environments/ 2> /dev/null)
	TARGET=$1

	for i in $VERSIONS
	do  
		
		if [ $TARGET  == $i  ]
		then
			echo -e "Removing Postgres installed by PGVM!\n"
		   	echo -e "	$i\n"
			rm -rf $pgvm_home/environments/$i
			exit 0
		elif [ $TARGET == "--all" ]
		then
			echo -e "Removing all Postgres installed by PGVM!\n"
			echo -e "$VERSIONS"
			rm -rf $pgvm_home/environments/*
			exit 0
		elif [ $TARGET == "--purge" ]
		then
			echo -e "Removing all Postgres installed and source by PGVM!\n"
			echo -e "$VERSIONS"
			rm -rf $pgvm_home/environments/*
			rm -rf $pgvm_home/src/*
			exit 0
		elif [ -z $TARGET ]
			 then
				echo -n -e "Choice Postgres version to remove or the options.\n"
				usage
				exit 0
		else
			usage
			exit 0	
		fi
    done	

		  
}
