#!/usr/bin/env bash

# Copyright (c) 2012 Dickson S. Guedes.
#
# This module is free software; you can redistribute it and/or modify it under
# the [PostgreSQL License](http://www.opensource.org/licenses/postgresql).
#
# Permission to use, copy, modify, and distribute this software and its
# documentation for any purpose, without fee, and without a written agreement is
# hereby granted, provided that the above copyright notice and this paragraph
# and the following two paragraphs appear in all copies.
#
# In no event shall Dickson S. Guedes be liable to any party for direct,
# indirect, special, incidental, or consequential damages, including lost
# profits, arising out of the use of this software and its documentation, even
# if Dickson S. Guedes has been advised of the possibility of such damage.
#
# Dickson S. Guedes specifically disclaims any warranties, including, but not
# limited to, the implied warranties of merchantability and fitness for a
# particular purpose. The software provided hereunder is on an "as is" basis,
# and Dickson S. Guedes has no obligations to provide maintenance, support,
# updates, enhancements, or modifications.

source $pgvm_home/include/sites

usage()
{
	echo """
Select a specific version of PostgreSQL to use.

Usage: pgvm use X.Y.Z

where X.Y.Z is the semantic version of a installed PostgreSQL

E.g.
   ~$ pgvm use 9.1.4

TIP: you can use 'pgvm list' to see the PostgreSQL
     installations available.
"""
}

use()
{
	version=$1
	if [[ $(echo ${#version}) -eq 3 ]]
	then
		list_last
	elif [[ $(echo ${#version}) -eq 1 \
		&& $(pgvm list|sed s/.\=\>//|cut -d "." -f 1|egrep ${version}) ]] 
	then
	    list_last
	fi

	[[ "x$version" == "x" ]] && usage && exit 1
	
	version_is_installed $version && create_symlinks || {
		echo "version $version is not installed"
		exit 1
	}

	echo "switched to $version"
}
